"""
xendris.outputs — Generated report artifacts (read-only at import time).

This package does NOT contain importable logic.
It marks the canonical output directory for reports generated by benchmarks,
campaigns, and the audit pipeline.

Typical files written here:
    false_formality_report.md
    false_formality_results.json
    atlas_points.json
    rag_status.md
"""
# No importable symbols — this is a directory marker only.
