"""Canonical blocked reason registry."""

from __future__ import annotations

from enum import Enum


class CanonicalBlockedReason(str, Enum):
    NO_BLOCK = "NO_BLOCK"
    MISSING_OBSERVABLE = "MISSING_OBSERVABLE"
    MISSING_FAILURE_CONDITION = "MISSING_FAILURE_CONDITION"
    MISSING_SOURCE_SUPPORT = "MISSING_SOURCE_SUPPORT"
    MISSING_BENCHMARK = "MISSING_BENCHMARK"
    MISSING_EXPERIMENTAL_DATA = "MISSING_EXPERIMENTAL_DATA"
    UNDETECTABLE_DELTA = "UNDETECTABLE_DELTA"
    UNPHYSICAL_PARAMETER = "UNPHYSICAL_PARAMETER"
    OUTSIDE_CLAIM_BOUNDARY = "OUTSIDE_CLAIM_BOUNDARY"
    OUTSIDE_ACTION_BOUNDARY = "OUTSIDE_ACTION_BOUNDARY"
    OUTSIDE_EXECUTION_BOUNDARY = "OUTSIDE_EXECUTION_BOUNDARY"
    OVERCLAIM = "OVERCLAIM"
    CONTRADICTION = "CONTRADICTION"
    NO_CUSTOMER = "NO_CUSTOMER"
    NO_PROBLEM = "NO_PROBLEM"
    NO_PAYMENT_SIGNAL = "NO_PAYMENT_SIGNAL"
    NO_CHANNEL_SIGNAL = "NO_CHANNEL_SIGNAL"
    NEGATIVE_UNIT_ECONOMICS = "NEGATIVE_UNIT_ECONOMICS"
    BLOCKING_RISK = "BLOCKING_RISK"
    NO_KILL_CRITERIA = "NO_KILL_CRITERIA"
    MODEL_OUTPUT_UNTRUSTED = "MODEL_OUTPUT_UNTRUSTED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
