"""Canonical evidence levels."""

from __future__ import annotations

from enum import Enum


class CanonicalEvidenceLevel(str, Enum):
    NO_EVIDENCE = "NO_EVIDENCE"
    HEURISTIC_ONLY = "HEURISTIC_ONLY"
    SYNTHETIC_ONLY = "SYNTHETIC_ONLY"
    SOURCE_BACKED_LIMITED = "SOURCE_BACKED_LIMITED"
    BENCHMARK_SUPPORTED = "BENCHMARK_SUPPORTED"
    EXPERIMENTAL_DATA_SUPPORTED = "EXPERIMENTAL_DATA_SUPPORTED"
    PAYMENT_SIGNAL = "PAYMENT_SIGNAL"
    REPEAT_PAYMENT_SIGNAL = "REPEAT_PAYMENT_SIGNAL"
    OPERATIONALLY_VALIDATED = "OPERATIONALLY_VALIDATED"
    EMPIRICALLY_UNGROUNDED = "EMPIRICALLY_UNGROUNDED"
    EMPIRICALLY_UNGROUNDED_METHOD_ONLY = "EMPIRICALLY_UNGROUNDED_METHOD_ONLY"
    ACCESSIBILITY_SCREEN_ONLY = "ACCESSIBILITY_SCREEN_ONLY"
    ACCESSIBILITY_SCREEN_FAILED = "ACCESSIBILITY_SCREEN_FAILED"


