"""Canonical permission grammar."""

from __future__ import annotations

from enum import Enum


class CanonicalPermission(str, Enum):
    IDEA_ALLOWED = "IDEA_ALLOWED"
    EXPLORE_ALLOWED = "EXPLORE_ALLOWED"
    TEST_DESIGN_ALLOWED = "TEST_DESIGN_ALLOWED"
    CLAIM_LIMITED_ALLOWED = "CLAIM_LIMITED_ALLOWED"
    CLAIM_BLOCKED = "CLAIM_BLOCKED"
    ACTION_LIMITED_ALLOWED = "ACTION_LIMITED_ALLOWED"
    ACTION_BLOCKED = "ACTION_BLOCKED"
    EXECUTION_ALLOWED = "EXECUTION_ALLOWED"
    EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
    SCALE_ALLOWED = "SCALE_ALLOWED"
    SCALE_BLOCKED = "SCALE_BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
