"""Canonical compatibility risk levels."""

from __future__ import annotations

from enum import Enum


class CanonicalRiskLevel(str, Enum):
    RISK_0_PRIVATE_THOUGHT = "RISK_0_PRIVATE_THOUGHT"
    RISK_1_INTERNAL_NOTE = "RISK_1_INTERNAL_NOTE"
    RISK_2_INTERNAL_RESEARCH = "RISK_2_INTERNAL_RESEARCH"
    RISK_3_PUBLIC_CONTENT = "RISK_3_PUBLIC_CONTENT"
    RISK_4_CLIENT_DELIVERABLE = "RISK_4_CLIENT_DELIVERABLE"
    RISK_5_FINANCIAL_RECOMMENDATION = "RISK_5_FINANCIAL_RECOMMENDATION"
    RISK_6_REAL_WORLD_ACTION = "RISK_6_REAL_WORLD_ACTION"
    RISK_7_AUTOMATED_EXECUTION = "RISK_7_AUTOMATED_EXECUTION"
    BUSINESS_RISK = "BUSINESS_RISK"
    TECHNICAL_RISK = "TECHNICAL_RISK"
    SCIENTIFIC_RISK = "SCIENTIFIC_RISK"

