"""Canonical support levels."""

from __future__ import annotations

from enum import Enum


class CanonicalSupportLevel(str, Enum):
    UNSUPPORTED = "UNSUPPORTED"
    HEURISTIC = "HEURISTIC"
    SYNTHETIC = "SYNTHETIC"
    SOURCE_LIMITED = "SOURCE_LIMITED"
    BENCHMARK = "BENCHMARK"
    EXPERIMENTAL = "EXPERIMENTAL"
    OPERATIONAL = "OPERATIONAL"
    UNSUPPORTED_FOR_GRADIENT_MECHANISM = "UNSUPPORTED_FOR_GRADIENT_MECHANISM"
    UNSUPPORTED_AS_PHYSICAL_MODEL = "UNSUPPORTED_AS_PHYSICAL_MODEL"
    NOT_YET_SUPPORTED = "NOT_YET_SUPPORTED"



