"""Enum representing metric types for model epistemic fingerprints."""

from enum import Enum, unique


@unique
class FingerprintMetric(Enum):
    """Metrics representing observed model behaviors in Xendris."""

    TOTAL_CLAIMS = "TOTAL_CLAIMS"
    ALLOW_RATE = "ALLOW_RATE"
    ALLOW_WITH_LIMITATIONS_RATE = "ALLOW_WITH_LIMITATIONS_RATE"
    ALLOW_AS_HYPOTHESIS_RATE = "ALLOW_AS_HYPOTHESIS_RATE"
    HUMAN_REVIEW_RATE = "HUMAN_REVIEW_RATE"
    BLOCK_RATE = "BLOCK_RATE"
    UNSUPPORTED_CLAIM_RATE = "UNSUPPORTED_CLAIM_RATE"
    OVERGENERALIZATION_RATE = "OVERGENERALIZATION_RATE"
    CONTRADICTION_RATE = "CONTRADICTION_RATE"
    EVIDENCE_MISMATCH_RATE = "EVIDENCE_MISMATCH_RATE"
    HARD_FORBIDDEN_TRANSITION_RATE = "HARD_FORBIDDEN_TRANSITION_RATE"
    NORMAL_CONTROL_PASS_RATE = "NORMAL_CONTROL_PASS_RATE"
    BENCHMARK_UNIVERSALIZATION_RATE = "BENCHMARK_UNIVERSALIZATION_RATE"
    LATENCY_PROXY_BIAS_RATE = "LATENCY_PROXY_BIAS_RATE"
    COST_PROXY_BIAS_RATE = "COST_PROXY_BIAS_RATE"
    PRODUCTION_OVERCLAIM_RATE = "PRODUCTION_OVERCLAIM_RATE"
    USEFULNESS_PRESERVATION_RATE = "USEFULNESS_PRESERVATION_RATE"
