"""
Reporting engine for Phygn case studies.

Generates auditable Markdown reports from computed results.
Reports include inputs, formulas, results, trace classification,
claim status, allowed/forbidden interpretations, and limitations.
"""

import os
from datetime import datetime, timezone

from phyng.case_studies.mesoscopic_interferometer import mesoscopic_interferometer_case
from phyng.case_studies.quantum_channel import quantum_channel_trace_case


def generate_mesoscopic_report(
    output_path: str = "reports/mesoscopic_negative_bound_report.md",
) -> str:
    """
    Generate a Markdown report for the mesoscopic interferometer case study.

    Args:
        output_path: File path where the report will be written.
            Parent directories are created automatically.

    Returns:
        The generated Markdown string.
    """
    result = mesoscopic_interferometer_case()
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    report = f"""# Mesoscopic Interferometer — Negative Bound Report

**Generated**: {timestamp}
**Case ID**: {result['case_id']}
**Phygn version**: 0.3.0

---

## Inputs

| Parameter | Value | Unit |
|-----------|-------|------|
| Mass (m) | {result['m_kg']:.0e} | kg |
| Scale (L) | {result['L_value_m']:.0e} | m |
| Scale type | {result['L_type']} | — |

## Formulas

$$
Q = \\frac{{\\lambda_C}}{{L}}, \\quad B = \\frac{{r_g}}{{L}}, \\quad QB = \\left(\\frac{{\\ell_P}}{{L}}\\right)^2
$$

## Results

| Quantity | Value |
|----------|-------|
| Q (quantum weight) | {result['Q']:.6e} |
| B (gravitational weight) | {result['B']:.6e} |
| QB (product) | {result['QB']:.6e} |
| QB valid | {result['qb_valid']} |

## Classification

| Field | Value |
|-------|-------|
| Scale review | {result['scale_review_status']} |
| Trace type | **{result['trace_type']}** |
| Claim status | {result['claim_status']} |

## Interpretation

### Allowed

> {result['allowed_interpretation']}

### Forbidden

> {result['forbidden_interpretation']}

## Limitations

- This result applies only to the specific mass and scale regime tested.
- B < 10⁻²⁰ means direct gravitational frontier effects are negligible.
- A NEGATIVE_BOUND_TRACE does **not** predict new decoherence — it bounds it away.
- No Predictive Gain is computed for this case (no baseline model comparison).
- The Q/B signature is a structural classification tool, not a prediction engine.

---

*Report generated by Phygn — Physical Signatures Lab*
"""

    # Write to file
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    return report


def generate_quantum_channel_report(
    p: float = 0.1,
    epsilon_exp: float = 1e-6,
    output_path: str = "reports/quantum_channel_depolarizing_report.md",
) -> str:
    """
    Generate a Markdown report for the depolarizing quantum channel case study.

    Args:
        p: Depolarizing parameter.
        epsilon_exp: Experimental resolution threshold.
        output_path: File path where the report will be written.

    Returns:
        The generated Markdown string.
    """
    result = quantum_channel_trace_case(p, epsilon_exp)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    report = f"""# Quantum Channel — Depolarizing Report

**Generated**: {timestamp}
**Case ID**: {result['case_id']}
**Phygn version**: 0.3.0

---

## Inputs

| Parameter | Value |
|-----------|-------|
| Depolarizing parameter (p) | {result['p']} |
| Experimental threshold (ε_exp) | {epsilon_exp:.0e} |

## Hypothesis

- **¬H** (null): p = 0 → identity channel, P(Y=0) = 1
- **H** (alternative): p > 0 → depolarization present

## Distributions

| Outcome | P(Y \\| H) | P(Y \\| ¬H) |
|---------|-----------|------------|
| Y = 0 | {result['p_h'][0]:.6f} | {result['p_not_h'][0]:.6f} |
| Y = 1 | {result['p_h'][1]:.6f} | {result['p_not_h'][1]:.6f} |

## Results

| Field | Value |
|-------|-------|
| τ_O(H) | {result['tau']:.6e} |
| Trace type | **{result['trace_type']}** |
| Claim status | {result['claim_status']} |

## Interpretation

> {result['interpretation']}

## Limitations

- This is a single-qubit, single-channel case study.
- The epistemic trace τ is computed via Jensen-Shannon divergence.
- A NULL_TRACE means the hypothesis leaves no operational footprint for this channel.
- A DETECTABLE_TRACE does not by itself prove new physics — it means the channel resolves H from ¬H.

---

*Report generated by Phygn — Physical Signatures Lab*
"""

    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    return report


def export_mesoscopic_json(
    output_path: str = "reports/mesoscopic_negative_bound.json",
) -> str:
    """
    Export the mesoscopic interferometer case study results as a JSON file.

    Args:
        output_path: File path where the JSON will be written.

    Returns:
        The generated JSON string.
    """
    import json
    result = mesoscopic_interferometer_case()
    data = {k: (v.tolist() if hasattr(v, "tolist") else v) for k, v in result.items()}
    serialized = json.dumps(data, indent=2)

    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(serialized)
    return serialized


def export_mesoscopic_latex(
    output_path: str = "reports/mesoscopic_negative_bound_snippet.tex",
) -> str:
    """
    Export the mesoscopic interferometer case study results as a LaTeX snippet (table).

    Args:
        output_path: File path where the LaTeX snippet will be written.

    Returns:
        The generated LaTeX string.
    """
    result = mesoscopic_interferometer_case()
    latex = f"""\\begin{{table}}[h]
\\centering
\\begin{{tabular}}{{llr}}
\\hline
Quantity & Symbol & Value \\\\
\\hline
Mass & $m$ & {result['m_kg']:.2e} kg \\\\
Scale & $L$ & {result['L_value_m']:.2e} m \\\\
Quantum Weight & $Q$ & {result['Q']:.6e} \\\\
Gravitational Weight & $B$ & {result['B']:.6e} \\\\
Product & $QB$ & {result['QB']:.6e} \\\\
QB Valid & — & {str(result['qb_valid'])} \\\\
Trace Type & — & \\texttt{{{result['trace_type']}}} \\\\
\\hline
\\end{{tabular}}
\\caption{{Mesoscopic Interferometer case study parameters and weights.}}
\\label{{tab:mesoscopic}}
\\end{{table}}"""

    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(latex)
    return latex


def export_quantum_channel_json(
    p: float = 0.1,
    epsilon_exp: float = 1e-6,
    output_path: str = "reports/quantum_channel_depolarizing.json",
) -> str:
    """
    Export the depolarizing quantum channel case study results as a JSON file.

    Args:
        p: Depolarizing parameter.
        epsilon_exp: Experimental resolution threshold.
        output_path: File path where the JSON will be written.

    Returns:
        The generated JSON string.
    """
    import json
    result = quantum_channel_trace_case(p, epsilon_exp)
    data = {k: (v.tolist() if hasattr(v, "tolist") else v) for k, v in result.items()}
    serialized = json.dumps(data, indent=2)

    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(serialized)
    return serialized


def export_quantum_channel_latex(
    p: float = 0.1,
    epsilon_exp: float = 1e-6,
    output_path: str = "reports/quantum_channel_depolarizing_snippet.tex",
) -> str:
    """
    Export the depolarizing quantum channel case study results as a LaTeX snippet (table).

    Args:
        p: Depolarizing parameter.
        epsilon_exp: Experimental resolution threshold.
        output_path: File path where the LaTeX snippet will be written.

    Returns:
        The generated LaTeX string.
    """
    result = quantum_channel_trace_case(p, epsilon_exp)
    latex = f"""\\begin{{table}}[h]
\\centering
\\begin{{tabular}}{{llr}}
\\hline
Quantity & Symbol & Value \\\\
\\hline
Depolarizing Parameter & $p$ & {result['p']:.4f} \\\\
Threshold & $\\epsilon_{{\\text{{exp}}}}$ & {epsilon_exp:.2e} \\\\
Trace $\\tau$ & $\\tau$ & {result['tau']:.6e} \\\\
Trace Type & — & \\texttt{{{result['trace_type']}}} \\\\
Claim Status & — & \\texttt{{{result['claim_status']}}} \\\\
\\hline
\\end{{tabular}}
\\caption{{Depolarizing Quantum Channel case study parameters and trace results.}}
\\label{{tab:quantum_channel}}
\\end{{table}}"""

    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(latex)
    return latex

