"""v5.9 candidate family registry."""

from __future__ import annotations

from phyng.candidates.schemas import CandidateFamilyRecord


def build_candidate_family_registry() -> list[CandidateFamilyRecord]:
    return [
        CandidateFamilyRecord(
            candidate_family_id="PHI_CURVATURE",
            display_name="Phi Curvature",
            status_before_v5_9="PARTIAL_SOURCE_IDENTITY_NO_ACTIVE_RULE",
            candidate_type="C_STRUCTURE_CANDIDATE",
            allowed_role="candidate_reformulation_only",
            blocked_roles=["PredictiveGateWithoutCStructure"],
            theoretical_basis="Curvature-like response in normalized condition space.",
            target_observable_classes=["VISIBILITY", "FRINGE_VISIBILITY", "INTERFERENCE_CONTRAST"],
            required_features=["condition_space_curvature_proxy", "normalized_physical_condition_vector"],
            optional_features=["temperature_K", "pressure_Pa", "time_s"],
            prediction_rule_summary=None,
            can_predict_without_ytrue=False,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=False,
            scientific_debt_blockers=["C-structure not defined for current dataset features."],
            notes=["Would become generic nonlinear curve fitting unless C-structure is specified."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="PHI_LOCALIZED_WINDOW",
            display_name="Phi Localized Window",
            status_before_v5_9="HEURISTIC_ONLY",
            candidate_type="C_STRUCTURE_CANDIDATE",
            allowed_role="candidate_reformulation_only",
            blocked_roles=["PostHocWindowSelection"],
            theoretical_basis="Localized degradation windows in experimental regimes.",
            target_observable_classes=["VISIBILITY", "INTERFERENCE_CONTRAST"],
            required_features=["predeclared_window_boundaries", "normalized_condition_axis"],
            optional_features=["mass_amu", "velocity_m_s", "heating_power_W"],
            prediction_rule_summary=None,
            can_predict_without_ytrue=False,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=False,
            scientific_debt_blockers=["No predeclared window boundaries for current dataset."],
            notes=["Post-hoc window fitting is leakage-prone."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="PHI_BANDPASS",
            display_name="Phi Bandpass",
            status_before_v5_9="HEURISTIC_ONLY",
            candidate_type="C_STRUCTURE_CANDIDATE",
            allowed_role="candidate_reformulation_only",
            blocked_roles=["GenericSmoothCurve"],
            theoretical_basis="Band-limited response in physical condition regimes.",
            target_observable_classes=["VISIBILITY", "INTERFERENCE_CONTRAST"],
            required_features=["predeclared_band_edges", "shared_normalized_condition_axis"],
            optional_features=["pressure_Pa", "mass_amu", "temperature_K"],
            prediction_rule_summary=None,
            can_predict_without_ytrue=False,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=False,
            scientific_debt_blockers=["No shared condition axis with predeclared bands."],
            notes=["Must beat generic bandpass controls before any claim."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="PHI_GRADIENT_METHOD_ONLY",
            display_name="Phi Gradient Method Only",
            status_before_v5_9="METHOD_ONLY_EMPIRICALLY_UNGROUNDED",
            candidate_type="METHOD_ONLY",
            allowed_role="negative_control_generator",
            blocked_roles=["ActivePhysicalCandidate"],
            theoretical_basis="Method fixture; not empirical candidate.",
            target_observable_classes=[],
            required_features=["SLOT_4_resolved_gradient_component"],
            optional_features=[],
            prediction_rule_summary=None,
            can_predict_without_ytrue=False,
            can_run_out_of_source=False,
            can_compare_to_baseline=False,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=False,
            scientific_debt_blockers=["SLOT_4 debt remains unresolved."],
            notes=["May be used as pipeline stress test only."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="B_SUPPRESSED",
            display_name="B Suppressed",
            status_before_v5_9="HEURISTIC_ONLY",
            candidate_type="C_STRUCTURE_CANDIDATE",
            allowed_role="candidate_reformulation_only",
            blocked_roles=["ExtremeParameterClaim"],
            theoretical_basis="Suppressed gravity-scale correction B = r_g / L.",
            target_observable_classes=["VISIBILITY"],
            required_features=["mass_kg", "operational_scale_L_m"],
            optional_features=["velocity_m_s"],
            prediction_rule_summary=None,
            can_predict_without_ytrue=False,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=True,
            scientific_debt_blockers=["No justified operational scale L for current records."],
            notes=["Likely numerically negligible in current regimes."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="QB_STRUCTURAL",
            display_name="QB Structural",
            status_before_v5_9="HEURISTIC_ONLY",
            candidate_type="C_STRUCTURE_CANDIDATE",
            allowed_role="candidate_reformulation_only",
            blocked_roles=["AdHocScale"],
            theoretical_basis="Combined invariant structure QB = (l_P/L)^2.",
            target_observable_classes=["VISIBILITY"],
            required_features=["mass_kg", "operational_scale_L_m"],
            optional_features=[],
            prediction_rule_summary=None,
            can_predict_without_ytrue=False,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=True,
            scientific_debt_blockers=["No non-ad-hoc L across dataset."],
            notes=["No arbitrary L is allowed."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="THRESHOLD_SATURATION",
            display_name="Threshold Saturation",
            status_before_v5_9="HEURISTIC_ONLY",
            candidate_type="C_STRUCTURE_CANDIDATE",
            allowed_role="candidate_reformulation_only",
            blocked_roles=["GenericSaturation"],
            theoretical_basis="Saturation near physical regime boundaries.",
            target_observable_classes=["VISIBILITY", "INTERFERENCE_CONTRAST"],
            required_features=["predeclared_threshold_variable", "shared_normalized_condition_axis"],
            optional_features=["heating_power_W", "laser_power_W"],
            prediction_rule_summary=None,
            can_predict_without_ytrue=False,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=False,
            scientific_debt_blockers=["No predeclared threshold variable spanning records."],
            notes=["Generic saturation baseline must remain comparator, not claim."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="DATA_DRIVEN_PHYSICS_BASELINE",
            display_name="Data Driven Physics Baseline",
            status_before_v5_9="BASELINE_CANDIDATE",
            candidate_type="DATA_BASELINE",
            allowed_role="baseline_comparator",
            blocked_roles=["FronteraCValidationCandidate"],
            theoretical_basis="Source-agnostic regression baseline over non-target condition features.",
            target_observable_classes=["VISIBILITY", "FRINGE_VISIBILITY", "INTERFERENCE_CONTRAST"],
            required_features=["non_target_condition_features"],
            optional_features=["molecule_class", "decoherence_mechanism_class"],
            prediction_rule_summary="Group-aware baseline regression using only non-target condition features.",
            can_predict_without_ytrue=True,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=False,
            scientific_debt_blockers=[],
            notes=["Not a Frontera C candidate; use as baseline/control only."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="C_COORDINATE_RESPONSE",
            display_name="C Coordinate Response",
            status_before_v5_9="THEORY_REFORMULATION_REQUIRED",
            candidate_type="C_STRUCTURE_CANDIDATE",
            allowed_role="candidate_reformulation_only",
            blocked_roles=["AdHocScale"],
            theoretical_basis="Q, B, u, w coordinates derived from justified mass and scale.",
            target_observable_classes=["VISIBILITY", "INTERFERENCE_CONTRAST"],
            required_features=["mass_kg", "operational_scale_L_m", "lambda_C_m", "r_g_m"],
            optional_features=["velocity_m_s"],
            prediction_rule_summary=None,
            can_predict_without_ytrue=False,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=True,
            scientific_debt_blockers=["Mass and operational scale L unavailable for all benchmark records."],
            notes=["No justified mass and L, no C-coordinate feature."],
        ),
        CandidateFamilyRecord(
            candidate_family_id="SOURCE_AGNOSTIC_DECOHERENCE_RESPONSE",
            display_name="Source Agnostic Decoherence Response",
            status_before_v5_9="PROMISING_BASELINE_OR_REFORMULATION",
            candidate_type="C_STRUCTURE_CANDIDATE",
            allowed_role="candidate_reformulation_only",
            blocked_roles=["IncompleteFeatureCoverage"],
            theoretical_basis="Predict response from physical condition variables independent of source identity.",
            target_observable_classes=["VISIBILITY", "FRINGE_VISIBILITY", "INTERFERENCE_CONTRAST"],
            required_features=["shared_numeric_condition_axis", "observable_mechanism_class"],
            optional_features=["heating_power_W", "velocity_m_s", "laser_power_W", "mass_amu"],
            prediction_rule_summary="Predeclared monotonic response over source-independent physical conditions.",
            can_predict_without_ytrue=True,
            can_run_out_of_source=True,
            can_compare_to_baseline=True,
            can_run_negative_controls=True,
            can_run_c_structure_ablation=False,
            scientific_debt_blockers=["No shared numeric condition axis across all accepted y_true records."],
            notes=["Can become a candidate only after common non-target features are completed."],
        ),
    ]
