"""Enum representing loggable trust event types in the Xendris Trust Ledger."""

from enum import Enum, unique


@unique
class TrustEventType(Enum):
    """Types of loggable decisions, events, and metrics in Xendris."""

    CLAIM_BOUNDARY_DECISION = "CLAIM_BOUNDARY_DECISION"
    SECTOR_TRANSITION_DECISION = "SECTOR_TRANSITION_DECISION"
    REPRESENTATION_CONSISTENCY_DECISION = "REPRESENTATION_CONSISTENCY_DECISION"
    MODEL_FINGERPRINT_SUMMARY = "MODEL_FINGERPRINT_SUMMARY"
    ROUTING_DECISION = "ROUTING_DECISION"
    EVIDENCE_BRIDGE_USED = "EVIDENCE_BRIDGE_USED"
    HUMAN_REVIEW_ROUTED = "HUMAN_REVIEW_ROUTED"
    CLAIM_BLOCKED = "CLAIM_BLOCKED"
    CLAIM_ALLOWED_WITH_LIMITATIONS = "CLAIM_ALLOWED_WITH_LIMITATIONS"
    CLAIM_ALLOWED_AS_HYPOTHESIS = "CLAIM_ALLOWED_AS_HYPOTHESIS"
    MODEL_SELECTED = "MODEL_SELECTED"
    MODEL_REJECTED = "MODEL_REJECTED"
    COST_ESTIMATE_RECORDED = "COST_ESTIMATE_RECORDED"
    LATENCY_ESTIMATE_RECORDED = "LATENCY_ESTIMATE_RECORDED"
    COUNCIL_ESCALATION = "COUNCIL_ESCALATION"
