"""RuntimeCandidate and RuntimeResponse definitions."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping


@dataclass(frozen=True)
class RuntimeCandidate:
    """An output candidate generated by a model for a specific request."""

    candidate_id: str
    model_id: str
    provider: str
    content: str
    raw_output_hash: str
    route_decision_ref: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class RuntimeResponse:
    """The final safety-audited output returned to the client/user."""

    response_id: str
    request_id: str
    decision: str  # ANSWER, ANSWER_WITH_LIMITATIONS, ANSWER_AS_HYPOTHESIS, HUMAN_REVIEW_REQUIRED, BLOCKED, NO_SAFE_MODEL_AVAILABLE
    final_content: str
    selected_model_id: str | None
    provider: str | None
    claim_decisions: tuple[dict[str, Any], ...] = ()
    sector_decisions: tuple[dict[str, Any], ...] = ()
    representation_decisions: tuple[dict[str, Any], ...] = ()
    ledger_record_ids: tuple[str, ...] = ()
    limitations: tuple[str, ...] = ()
    human_review_required: bool = False
    blocked: bool = False
    reason: str = ""
    audit_tags: tuple[str, ...] = ()
