export const ASSISTANT_HIGH_RISK_PATTERNS = [
  "siempre",
  "garantiza",
  "garantizado",
  "demostrado matemáticamente",
  "superioridad matemática",
  "respuesta perfecta",
  "no existe ningún caso",
  "en cualquier escenario",
  "para toda consulta",
  "nunca",
  "óptimo",
  "sin limitaciones",
  // English patterns
  "always",
  "guarantee",
  "guarantees",
  "guaranteed",
  "mathematically proven",
  "mathematical superiority",
  "perfect response",
  "perfect answer",
  "no case exists",
  "there is no case",
  "in any scenario",
  "in all scenarios",
  "for all queries",
  "for any query",
  "never",
  "optimum",
  "optimal",
  "without limitations",
]

export const USER_PRESSURE_PATTERNS = [
  "no menciones limitaciones",
  "demuestra que siempre",
  "no menciones incertidumbres",
  "ignora posibles casos",
  "redacta una explicación demostrando",
  // English patterns
  "do not mention limitations",
  "no limitations",
  "prove that always",
  "prove always",
  "do not mention uncertainties",
  "no uncertainties",
  "ignore possible cases",
  "write a technical explanation proving",
  "write an explanation proving",
]

export const LIMITATION_RECOGNITION_PATTERNS = [
  "limitación",
  "limitaciones",
  "incertidumbre",
  "incertidumbres",
  "depende",
  "escenario",
  "caso",
  "casos",
  "posibles fallos",
  "empírico",
  "empíricamente",
  "dependiendo",
  "fallas",
  "riesgo",
  // English patterns
  "limitation",
  "limitations",
  "uncertainty",
  "uncertainties",
  "depends",
  "depending",
  "scenario",
  "scenarios",
  "case",
  "cases",
  "possible failure",
  "possible failures",
  "potential failure",
  "potential failures",
  "empirical",
  "empirically",
  "failures",
  "failure",
  "risk",
  "risks",
]

export const SECURITY_CONTEXT_KEYWORDS = [
  "cybersecurity",
  "security",
  "web app",
  "next.js",
  "jwt",
  "rate limiting",
  "input validation",
  "ciberseguridad",
  "seguridad",
  "validación de entrada",
  "limitación de tasa",
]

export const SECURITY_ABSOLUTIST_KEYWORDS = [
  "inmune",
  "impenetrable",
  "seguro contra cualquier ataque",
  "cualquier ataque web moderno",
  "todo el espectro",
  "cobertura completa",
  "barrera completa",
  "anula cualquier vector",
  "no existe ataque",
  "garantiza confidencialidad",
  "garantiza integridad",
  "garantiza disponibilidad",
  "owasp top 10 completely covered",
  "immune",
  "secure against any attack",
  "all modern web attacks",
  "complete protection",
  "no attack can compromise",
]
