"""Curated candidate source queue for v5.7.1."""

from __future__ import annotations

from phyng.source_acquisition.schemas import SourceAcquisitionQueueItem
from phyng.source_acquisition.seed_queries import SEED_QUERIES


def build_candidate_sources() -> list[SourceAcquisitionQueueItem]:
    return [
        SourceAcquisitionQueueItem(
            acquisition_id="VD-SRC-v5_7_1-001-BREZGER-2002-TALBOT-LAU",
            priority="CRITICAL",
            source_title_candidate="Matter-wave interferometer for large molecules",
            authors_candidate=["B. Brezger", "L. Hackermueller", "S. Uttenthaler", "J. Petschinka", "M. Arndt", "A. Zeilinger"],
            year_candidate=2002,
            publication_candidate="Physical Review Letters 88, 100404",
            doi_candidate="10.1103/PhysRevLett.88.100404",
            arxiv_candidate="quant-ph/0202158",
            url_candidate="https://arxiv.org/abs/quant-ph/0202158",
            search_queries=[SEED_QUERIES[2], SEED_QUERIES[3]],
            reason_for_relevance="Reports C70 Talbot-Lau interference visibility and velocity dependence.",
            target_observable_classes=["FRINGE_VISIBILITY", "MATTER_WAVE_VISIBILITY"],
            expected_conditions=["velocity_m_s", "molecule", "grating_period_m"],
            source_identity_status="RESOLVED_COMPLETE",
            availability_status="OPEN_ACCESS_CONFIRMED",
            likely_observable_location="abstract/figures/captions with fringe visibility",
            manual_action_required="Download source PDF and inspect figures/captions for numeric visibility rows.",
        ),
        SourceAcquisitionQueueItem(
            acquisition_id="VD-SRC-v5_7_1-002-GERLICH-2011-LARGE-ORGANIC",
            priority="CRITICAL",
            source_title_candidate="Quantum interference of large organic molecules",
            authors_candidate=["S. Gerlich", "S. Eibenberger", "M. Tomandl", "S. Nimmrichter", "K. Hornberger", "P. J. Fagan", "J. Tuxen", "M. Mayor", "M. Arndt"],
            year_candidate=2011,
            publication_candidate="Nature Communications 2, 263",
            doi_candidate="10.1038/ncomms1263",
            arxiv_candidate=None,
            url_candidate="https://doi.org/10.1038/ncomms1263",
            search_queries=[SEED_QUERIES[3], "Gerlich quantum interference large organic molecules visibility"],
            reason_for_relevance="KDTLI large-molecule interference likely contains visibility/contrast figures.",
            target_observable_classes=["FRINGE_VISIBILITY", "INTERFERENCE_CONTRAST"],
            expected_conditions=["mass_amu", "velocity_m_s", "molecule"],
            source_identity_status="RESOLVED_COMPLETE",
            availability_status="REQUIRES_DOWNLOAD",
            likely_observable_location="figures/results section",
            manual_action_required="Download paper and supplementary material if present.",
        ),
        SourceAcquisitionQueueItem(
            acquisition_id="VD-SRC-v5_7_1-003-EIBENBERGER-2013-10000AMU",
            priority="HIGH",
            source_title_candidate="Matter-wave interference with particles selected from a molecular library with masses exceeding 10000 amu",
            authors_candidate=["Sandra Eibenberger", "Stefan Gerlich", "Markus Arndt", "Marcel Mayor", "Jens Tuexen"],
            year_candidate=2013,
            publication_candidate="Physical Chemistry Chemical Physics 15, 14696-14700",
            doi_candidate="10.1039/C3CP51500A",
            arxiv_candidate="1310.8343",
            url_candidate="https://arxiv.org/abs/1310.8343",
            search_queries=[SEED_QUERIES[3], "Eibenberger molecular library 10000 amu visibility"],
            reason_for_relevance="Reports high-contrast molecular matter-wave interference for massive molecules.",
            target_observable_classes=["INTERFERENCE_CONTRAST", "MATTER_WAVE_VISIBILITY"],
            expected_conditions=["mass_amu", "molecule", "velocity_m_s"],
            source_identity_status="RESOLVED_COMPLETE",
            availability_status="OPEN_ACCESS_CONFIRMED",
            likely_observable_location="figures/captions/results section",
            manual_action_required="Download arXiv/PCCP source and inspect figures for extractable contrast.",
        ),
        SourceAcquisitionQueueItem(
            acquisition_id="VD-SRC-v5_7_1-004-JUFFMANN-2012-REALTIME",
            priority="HIGH",
            source_title_candidate="Real-time single-molecule imaging of quantum interference",
            authors_candidate=["Thomas Juffmann", "Adriana Milic", "Michael Muellneritsch", "Peter Asenbaum", "Alexander Tsukernik", "Jens Tuexen", "Marcel Mayor", "Ori Cheshnovsky", "Markus Arndt"],
            year_candidate=2012,
            publication_candidate="Nature Nanotechnology",
            doi_candidate="10.1038/nnano.2012.34",
            arxiv_candidate="1402.1867",
            url_candidate="https://arxiv.org/abs/1402.1867",
            search_queries=["real-time single molecule imaging quantum interference visibility", "phthalocyanine molecule interference visibility"],
            reason_for_relevance="Single-molecule interference imaging may provide contrast/visibility observables.",
            target_observable_classes=["INTERFERENCE_CONTRAST", "MATTER_WAVE_VISIBILITY"],
            expected_conditions=["molecule", "mass_amu", "grating_period_m"],
            source_identity_status="RESOLVED_COMPLETE",
            availability_status="OPEN_ACCESS_CONFIRMED",
            likely_observable_location="figures/images/captions",
            manual_action_required="Download source and inspect figure/caption data; may require image analysis.",
        ),
        SourceAcquisitionQueueItem(
            acquisition_id="VD-SRC-v5_7_1-005-HACKERMUELLER-2003-BIOMOLECULES",
            priority="HIGH",
            source_title_candidate="The wave nature of biomolecules and fluorofullerenes",
            authors_candidate=["Lucia Hackermueller", "Stefan Uttenthaler", "Klaus Hornberger", "Elisabeth Reiger", "Bjoern Brezger", "Anton Zeilinger", "Markus Arndt"],
            year_candidate=2003,
            publication_candidate="Physical Review Letters 91, 090408",
            doi_candidate="10.1103/PhysRevLett.91.090408",
            arxiv_candidate="quant-ph/0309016",
            url_candidate="https://arxiv.org/abs/quant-ph/0309016",
            search_queries=["wave nature biomolecules fluorofullerenes visibility", SEED_QUERIES[2]],
            reason_for_relevance="Reports biomolecule/fluorofullerene interference visibility in Talbot-Lau setup.",
            target_observable_classes=["FRINGE_VISIBILITY", "INTERFERENCE_CONTRAST"],
            expected_conditions=["molecule", "mass_amu", "velocity_m_s"],
            source_identity_status="RESOLVED_COMPLETE",
            availability_status="OPEN_ACCESS_CONFIRMED",
            likely_observable_location="figures/results section",
            manual_action_required="Download arXiv/PRL source and inspect visibility values.",
        ),
        SourceAcquisitionQueueItem(
            acquisition_id="VD-SRC-v5_7_1-006-ARNDT-1999-C60",
            priority="MEDIUM",
            source_title_candidate="Wave-particle duality of C60 molecules",
            authors_candidate=["Markus Arndt", "Olaf Nairz", "Julian Vos-Andreae", "Claudia Keller", "Gerbrand van der Zouw", "Anton Zeilinger"],
            year_candidate=1999,
            publication_candidate="Nature 401, 680-682",
            doi_candidate="10.1038/44348",
            arxiv_candidate=None,
            url_candidate="https://doi.org/10.1038/44348",
            search_queries=["Wave-particle duality of C60 molecules visibility", "C60 molecule interference visibility Nature 1999"],
            reason_for_relevance="Foundational C60 molecule interference source; may contain fringe visibility/contrast figures.",
            target_observable_classes=["FRINGE_VISIBILITY", "MATTER_WAVE_VISIBILITY"],
            expected_conditions=["molecule", "velocity_m_s"],
            source_identity_status="RESOLVED_COMPLETE",
            availability_status="PAYWALL_LIKELY",
            likely_observable_location="Nature figures/captions",
            manual_action_required="Acquire PDF via local/library access.",
        ),
    ]
